language: node_js
node_js: stable
services:
  - docker

before_install:
  - npm install

script:
  - npm run build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t tiannengyu/docker-test:latest .
  - docker push tiannengyu/docker-test:latest